FROM mysql:5.7.22
RUN apt-get update && apt-get upgrade -y && echo "mysql-server mysql-server/root_password password root" | debconf-set-selections
RUN echo "mysql-server mysql-server/root_password_again password root" | debconf-set-selections
RUN apt-get install -y mysql-server 

RUN mkdir -p           /etc/service/mysql
ADD mysql/build/mysql.sh  /etc/service/mysql/run
RUN chmod +x        /etc/service/mysql/run

RUN mkdir -p        /var/lib/mysql/
RUN chmod -R 755    /var/lib/mysql/


RUN mkdir -p           /etc/service/mysql
ADD mysql/build/mysql.sh  /etc/service/mysql/run
RUN chmod +x        /etc/service/mysql/run

RUN mkdir -p        /var/lib/mysql/
RUN chmod -R 755    /var/lib/mysql/

ADD mysql/etc/my_init.d/99_mysql_setup.sh /etc/my_init.d/99_mysql_setup.sh
RUN chmod +x /etc/my_init.d/99_mysql_setup.sh
RUN service mysql start
EXPOSE 3306
VOLUME ./dbdata:/var/lib/mysql
CMD ["/usr/bin/mysqld_safe"]

