version: '3'
services:

  #Redmine storage and RVM
  app:
    build:
      context: .
      dockerfile: Dockerfile_redmine
    image: ubuntu:16.04
    container_name: redmine
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: redmine
      SERVICE_TAGS: dev
    working_dir: /var/data/redmine
    volumes:
      - ./redmine:/var/data/redmine
      - ./nginx/redmine.conf:/etc/nginx/conf.d/redmine.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/database.yml:/var/data/redmine/config/database.yml 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: mysql:5.7.31
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./redmine:/var/data/redmine
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
