version: '3'
services:

  #Redmine storage and RVM
  app:
    build:
      context: .
      dockerfile: Dockerfile_redmine
    image: ubuntu:18.04
    container_name: redmine
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: redmine
      SERVICE_TAGS: dev
    working_dir: /var/data/redmine
    volumes:
      - ./redmine:/var/data/redmine
      - ./nginx/nginx.conf:/opt/nginx/conf/nginx.conf
#    command: apt-get update && apt-get install -y libmysqlclient-dev git-core subversion imagemagick libmagickwand-dev libcurl4-openssl-dev curl
#    command: command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
#    command: command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
#    command: command curl -sSL https://rvm.io/mpapis.asc | gpg --import - && curl -L https://get.rvm.io | bash -s stable
#    command: source /usr/local/rvm/scripts/rvm && echo '[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"' >> ~/.bashrc
#    command: command curl -sSL https://rvm.io/mpapis.asc | gpg --import - && rvm get head && rvm install ruby-2.3
#    command: apt-get install -y libcurl4-gnutls-dev
#    command: gem install passenger --no-ri --no-rdoc
#    command: passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx
#    command: /opt/nginx/sbin/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  #Nginx Service
#  webserver:
#    build:
#      context: .
#      dockerfile: Dockerfile_nginx
#    image: nginx:alpine
#    container_name: webserver
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/opt/nginx/conf/nginx.conf
#    networks:
#      - app-network

  #MySQL Service
#  db:
#    build:
#      context: .
#      dockerfile: Dockerfile_mysql
#    image: mysql:5.7.22
#    container_name: db
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: redmine
#      MYSQL_ROOT_PASSWORD: root
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - dbdata:/var/lib/mysql/
#      - redmine:/var/data/redmine/	
#    networks:
#      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
