FROM ubuntu:16.04 

ENV WORKDIR=/var/data/redmine

RUN apt-get update -q && \
    apt-get install -qy curl libmysqlclient-dev nano imagemagick libmagickwand-dev libcurl4-openssl-dev software-properties-common


RUN apt-add-repository -y ppa:rael-gc/rvm && \
    apt-get update -q && \
    apt-get install -y rvm

RUN command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

RUN command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

RUN curl -L https://get.rvm.io | bash -s stable

RUN ./usr/local/rvm/scripts/rvm

RUN echo '[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"' >> ~/.bashrc

RUN command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

RUN ln -s /usr/local/rvm/bin/rvm /usr/bin/rvm

RUN /usr/local/rvm/bin/rvm get head

RUN /usr/local/rvm/bin/rvm install 2.5.0

RUN /usr/local/rvm/bin/rvm use 2.5.0 --default

RUN apt-get install -y dirmngr gnupg && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 && \
    apt-get install -y apt-transport-https ca-certificates && \
    echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list && \
    apt-get update -q && apt-get install -y nginx-extras passenger

RUN apt-get install -y build-essential imagemagick libmagickwand-dev libcurl4-gnutls-dev rubygems ruby-dev tzdata

RUN gem install bundler mysql2 --no-ri --no-rdoc 

CMD ["nginx", "-g", "daemon off;"]

RUN chown -R 0775 tmp log

###################################################################
#RUN command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

#RUN command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -


#RUN curl -L https://get.rvm.io | bash -s stable

#RUN ./usr/local/rvm/scripts/rvm

#RUN echo '[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"' >> ~/.bashrc

#RUN command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

#RUN ln -s /usr/local/rvm/bin/rvm /usr/bin/rvm

#RUN /usr/local/rvm/bin/rvm get head

#RUN /usr/local/rvm/bin/rvm install ruby-2.3

#RUN apt-get install -y libcurl4-gnutls-dev rubygems ruby-dev

#RUN gem install passenger --no-ri --no-rdoc

#RUN passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx

#RUN ln -s /opt/nginx/sbin/nginx /usr/bin/nginx

#RUN gem install bundler --no-ri --no-rdoc


