production:
  adapter: mysql2
  database: redmine
  host: db
  username: root
  password: ""
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8

development:
  adapter: mysql2
  database: redmine
  host: db
  username: root
  password: ""
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8

