production:
  adapter: mysql2
  database: redmine
  host: db
  username: root
  password: root
  encoding: utf8

development:
  adapter: mysql2
  database: redmine 
  host: db
  username: root
  password: root
  encoding: utf8
